plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
        namespace 'com.mulheres'
    compileSdk 36

    defaultConfig {
                applicationId "com.mulheres"
        minSdk 23
        targetSdk 36

        versionCode 32
        versionName "32"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
    compose false
    viewBinding true
}

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    // =========================================================
    // ANDROIDX
    // =========================================================

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.12.1'


    // =========================================================
    // MATERIAL DESIGN
    // =========================================================

    implementation 'com.google.android.material:material:1.12.0'


    // =========================================================
    // BIOMETRIA
    // =========================================================

    implementation 'androidx.biometric:biometric:1.1.0'


    // =========================================================
    // LOCALIZAÇÃO
    // =========================================================

    implementation 'com.google.android.gms:play-services-location:21.3.0'


    // =========================================================
    // SEGURANÇA
    // =========================================================

    implementation 'androidx.security:security-crypto:1.1.0-alpha06'


    // =========================================================
    // LIFECYCLE
    // =========================================================

    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.1'


    // =========================================================
    // MEDIA3
    // =========================================================

    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-ui:1.8.0'
    implementation 'androidx.media3:media3-common:1.8.0'
    implementation 'androidx.media3:media3-session:1.8.0'


    // =========================================================
    // ZIP4J
    // =========================================================

    implementation 'net.lingala.zip4j:zip4j:2.11.5'


    // =========================================================
    // TESTES
    // =========================================================

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'

    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}